# Generated by Django 3.1.3 on 2020-11-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='rain',
        ),
        migrations.AddField(
            model_name='forecast',
            name='time_made',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
