# Generated by Django 3.1.3 on 2020-11-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20201129_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='time_made',
            new_name='time_cast',
        ),
    ]
