# Generated by Django 3.1.3 on 2020-12-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_forecast_feeltemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='feeltemp',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='forecast',
            old_name='temperature',
            new_name='low',
        ),
    ]
