# Generated by Django 3.1.3 on 2020-12-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_auto_20201207_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='time_cast',
        ),
    ]
